name: ci
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          TS_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          powershell.exe -File build_assets3.ps1
